# -*- coding: utf-8 -*-
"""model3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IAHmAqIZGLwc-7hmANyUIotYqkiv7Ge
"""

from keras import layers, models
from keras.applications import VGG16


def build_model(input_shape=(150, 150, 3)):
    # Load the pre-trained VGG16 model
    conv_base = VGG16(
        weights='imagenet',
        include_top=False,
        input_shape=input_shape
    )

    # Freeze the convolutional base
    conv_base.trainable = True

    # Freeze all layers except the last 3 convolutional layers
    for layer in conv_base.layers[:-4]:
        layer.trainable = False

    # Build the model
    model = models.Sequential()
    model.add(conv_base)
    model.add(layers.Flatten())
    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.Dense(1, activation='sigmoid'))

    return model