# -*- coding: utf-8 -*-
"""evaluate_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IAHmAqIZGLwc-7hmANyUIotYqkiv7Ge
"""

from keras.models import load_model
from tensorflow.keras.preprocessing.image import ImageDataGenerator

def evaluate_model(model_path, test_dir):
    # Load the saved model
    model = load_model(model_path)

    # Load the test dataset
    test_datagen = ImageDataGenerator(rescale=1./255)
    test_generator = test_datagen.flow_from_directory(
        test_dir,
        target_size=(150, 150),
        batch_size=20,
        class_mode='binary')

    # Evaluate the model on the test data
    loss, accuracy = model.evaluate(test_generator)

    print(f'Test loss: {loss}')
    print(f'Test accuracy: {accuracy}')