# -*- coding: utf-8 -*-
"""streamlit_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IAHmAqIZGLwc-7hmANyUIotYqkiv7Ge
"""

import streamlit as st
from keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

# Load the trained model
model_path = 'models/cats_and_dogs_small_1.h5'
model = load_model(model_path)

# Function to preprocess the image
def preprocess_image(image_path):
    img = image.load_img(image_path, target_size=(150, 150))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    return img_array

# Define the labels
labels = {0: 'Cat', 1: 'Dog'}

# Streamlit app
def main():
    st.title("Cat vs Dog Image Classifier")
    st.write("Upload an image and the model will predict whether it's a cat or a dog.")

    uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg"])

    if uploaded_file is not None:
        # Display the uploaded image
        st.image(uploaded_file, caption='Uploaded Image', use_column_width=True)

        # Make a prediction
        img_array = preprocess_image(uploaded_file)
        prediction = model.predict(img_array)
        predicted_class = np.argmax(prediction)
        predicted_label = labels[predicted_class]

        # Display the prediction
        st.write(f"Prediction: {predicted_label} (Confidence: {prediction[0][predicted_class]:.2f})")

if __name__ == "__main__":
    main()