# -*- coding: utf-8 -*-
"""preprocess_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17IAHmAqIZGLwc-7hmANyUIotYqkiv7Ge
"""

import os
import shutil
from keras.preprocessing import image

def create_directories(base_dir):
    os.makedirs(base_dir, exist_ok=True)
    train_dir = os.path.join(base_dir, 'train')
    validation_dir = os.path.join(base_dir, 'validation')
    test_dir = os.path.join(base_dir, 'test')
    os.makedirs(train_dir, exist_ok=True)
    os.makedirs(validation_dir, exist_ok=True)
    os.makedirs(test_dir, exist_ok=True)
    return train_dir, validation_dir, test_dir

def copy_images(src_dir, dst_dir, start_index, end_index):
    fnames = ['{}.jpg'.format(i) for i in range(start_index, end_index)]
    for fname in fnames:
        src = os.path.join(src_dir, fname)
        dst = os.path.join(dst_dir, fname)
        try:
            img = image.load_img(src)
            shutil.copyfile(src, dst)
        except Exception as e:
            print(f"Error loading image: {src}, Error message: {str(e)}")

def preprocess_data():
    base_dir = 'data/processed/cats_and_dogs_small'
    train_dir, validation_dir, test_dir = create_directories(base_dir)

    # Directories for our training, validation, and test splits
    train_cats_dir = os.path.join(train_dir, 'cats')
    train_dogs_dir = os.path.join(train_dir, 'dogs')
    validation_cats_dir = os.path.join(validation_dir, 'cats')
    validation_dogs_dir = os.path.join(validation_dir, 'dogs')
    test_cats_dir = os.path.join(test_dir, 'cats')
    test_dogs_dir = os.path.join(test_dir, 'dogs')

    for directory in [train_cats_dir, train_dogs_dir, validation_cats_dir, validation_dogs_dir, test_cats_dir, test_dogs_dir]:
        os.makedirs(directory, exist_ok=True)

    # Source directories
    cat_dataset_dir = 'data/raw/PetImages/Cat'
    dog_dataset_dir = 'data/raw/PetImages/Dog'

    copy_images(cat_dataset_dir, train_cats_dir, 0, 1000)
    copy_images(cat_dataset_dir, validation_cats_dir, 1000, 1500)
    copy_images(cat_dataset_dir, test_cats_dir, 1500, 2000)

    copy_images(dog_dataset_dir, train_dogs_dir, 0, 1000)
    copy_images(dog_dataset_dir, validation_dogs_dir, 1000, 1500)
    copy_images(dog_dataset_dir, test_dogs_dir, 1500, 2000)

def main():
    preprocess_data()

if __name__ == "__main__":
    main()